### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by nandalopes** [nandalopes/dotfiles#1]
Things on my huge, personal dotfiles that may be useful to bring here:

- [ ] Add [asdf](http://asdf-vm.com/) and [direnv](http://direnv.net/) config. All-in-one version manager plus direnv to optimization
  - [ ] Need to install direnv system bin
- [ ] Add [fzf](http://github.com/junegunn/fzf) config at `~/.config/fzf`
- [ ] Put theme colors (solarized, gruvbox and dracula) on `.chezmoidata.yaml`
- [ ] Add [kitty terminal](http://github.com/kovidgoyal/kitty) config
  - [ ] With solarized theme?
  - [ ] With support to interactive theming?
  - [ ] With dracula and solarized dark diff.conf?
- [ ] Add `~/.aliases` with zsh code to source it, maybe moving zsh and bash compatible to it
