### ISSUE TITLE
ToDo List (mine branch)

### ISSUE THREAD

**Issue by nandalopes** [nandalopes/dotfiles#2]
- [ ] Add vimtex config
- [ ] Add zathura pdf viewer config
- [ ] Learn to use a LSP to Latex
